app:
  jwt:
    secret: "6S395P93478F2JF1CAZ66I77CH457477U508K61EP01UI531DCG225864205O8UK"
    expire-seconds: 3600
    authorization-header: Authorization

  redis:
    stream-key: "stream:events"
    group: "group:main"

  s3:
    access-key: "your-access-key"
    secret-key: "your-secret-key"
    endpoint: "end-point"
    region: "region"
    bucket: "bucket"

  path:
    root: "/your-root"